services:
  telemetry-ingester:
    build: ./telemetry-ingester
    command: -c /etc/telemetry-ingester
    restart: unless-stopped
    environment:
      CHIRPSTACK_API_TOKEN_FILE: /run/secrets/chirpstack-api-token
    secrets: 
      - chirpstack-api-token
    volumes:
      - ./configuration/telemetry-ingester:/etc/telemetry-ingester
    depends_on:
      - influxdb2

  # https://docs.influxdata.com/influxdb/v2/install/use-docker-compose
  influxdb2:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: token
      DOCKER_INFLUXDB_INIT_ORG: organization
      DOCKER_INFLUXDB_INIT_BUCKET: chirpstack
      TZ: Europe/Rome
    volumes:
      - influxdb2-data:/var/lib/influxdb2


  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker
  # https://grafana.com/docs/grafana/latest/administration/provisioning
  grafana:
    image: grafana/grafana:12.2
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      INFLUXDB_ENDPOINT: influxdb2:8086
      INFLUXDB_ORG: organization
      INFLUXDB_TOKEN: token
    volumes:
      - ./configuration/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./configuration/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./configuration/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./configuration/grafana/dashboards:/etc/dashboards
      - grafana-storage:/var/lib/grafana

secrets:
  chirpstack-api-token:
    file: .env.chirpstack-api-token

volumes:
  grafana-storage:
  influxdb2-data:
