# Log level: ERROR, WARNING, INFO, DEBUG
log = "INFO"


# Redis database for sourcing frame data
[redis]

# The endpoint of ChirpStack's Redis instance
endpoint = "localhost:6379"

# The Redis data stream to read from
stream = "device:stream:frame"


# Time-series database for the metrics collection system
[influxdb]

# The endpoint of your InfluxDB instance
endpoint = "localhost:8086"

# InfluxDB authentication token
token = "token"

# InfluxDB organization
org = "organization"

# InfluxDB bucket where data is stored
bucket = "chirpstack"
