apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://$INFLUXDB_ENDPOINT
    uid: P5697886F9CA74929
    jsonData:
      version: Flux
      organization: $INFLUXDB_ORG
    secureJsonData:
      token: $INFLUXDB_TOKEN
